jobs:
  test:
    environment: release
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: setup repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm run lint:eslint
      - run: npm run lint:tsc
      - run: npm run lint:cspell
      - run: npm run test:mocha
      - run: npm run build
    timeout-minutes: 10
name: Test and build
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
